apiVersion: v1
kind: Pod
metadata:
  name: posts
  # labels:
  #   name: myapp
spec:
  containers:
  - name: posts
    image: acanakdas/posts
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    # ports:
    #   - containerPort: <Port>
